name: CI/CD

on:
  push:

jobs:

  test-ubuntu:
    name: Ubuntu
    uses: StudioLE/Actions/.github/workflows/dotnet-test.yml@v6
    with:
      project: ""
      os: ubuntu-latest
      nuget_feed: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      nuget_username: ${{ github.repository_owner }}
      pack: true
    secrets:
      nuget_password: ${{ secrets.PACKAGES_TOKEN }}

  test-windows:
    name: Windows
    if: ${{ github.ref_type == 'branch' && contains(fromJSON('["main", "alpha", "beta", "release"]'), github.ref_name) }}
    uses: StudioLE/Actions/.github/workflows/dotnet-test.yml@v6
    with:
      project: ""
      os: windows-latest
      nuget_feed: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      nuget_username: ${{ github.repository_owner }}
    secrets:
      nuget_password: ${{ secrets.PACKAGES_TOKEN }}

  documentation:
    name: Documentation
    if: ${{ github.ref_type == 'branch' && contains(fromJSON('["main", "alpha", "beta", "release"]'), github.ref_name) }}
    uses: StudioLE/Actions/.github/workflows/illuminate-generate.yml@v6
    with:
      project: ""
      os: ubuntu-latest
      nuget_feed: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      nuget_username: ${{ github.repository_owner }}
      latest: ${{ github.ref_type == 'branch' && github.ref_name == 'release' }}
      source: "*/src/bin/Release/*/StudioLE.*.dll"
      section: "verify"
    secrets:
      nuget_password: ${{ secrets.PACKAGES_TOKEN }}

  release:
    name: Release
    if: ${{ github.ref_type == 'branch' && contains(fromJSON('["main", "alpha", "beta", "release"]'), github.ref_name) }}
    needs:
    - test-ubuntu
    uses: StudioLE/Actions/.github/workflows/surveyor-release.yml@v6
    with:
      nuget_feed: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      nuget_username: ${{ github.repository_owner }}
    secrets:
      nuget_password: ${{ secrets.PACKAGES_TOKEN }}

  push-tests:
    name: Test Results
    if: ${{ always() }}
    needs:
    - test-ubuntu
    uses: StudioLE/Actions/.github/workflows/push-to-repo.yml@v6
    with:
      repo: StudioLE/Tests
      artifact: Tests-Linux-X64
      rm: "${{ github.repository }}/${{ github.run_id }}"
      path: "${{ github.repository }}/${{ github.run_id }}"
      message: "feat(${{ github.repository }}): Added test results for ${{ github.sha }}"
    secrets:
      repo_token: ${{ secrets.TESTS_TOKEN }}

  push-packages-github:
    name: GitHub Packages
    needs:
    - release
    uses: StudioLE/Actions/.github/workflows/push-to-nuget.yml@v6
    with:
      nuget_feed: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      nuget_username: ${{ github.repository_owner }}
    secrets:
      nuget_password: ${{ secrets.GITHUB_TOKEN }}

  push-packages-nuget:
    name: NuGet Packages
    if: ${{ ! contains(needs.release.outputs.version, '-') }}
    needs:
    - release
    uses: StudioLE/Actions/.github/workflows/push-to-nuget.yml@v6
    with:
      nuget_feed: https://api.nuget.org/v3/index.json
      nuget_username: ${{ github.repository_owner }}
    secrets:
      nuget_password: ${{ secrets.NUGET_TOKEN }}

  push-documentation:
    name: Documentation
    needs:
    - documentation
    - release
    uses: StudioLE/Actions/.github/workflows/push-to-repo.yml@v6
    with:
      repo: StudioLE/Documentation
      artifact: Documentation
      path: ""
      message: "feat(verify): Added documentation for v${{ needs.release.outputs.version }}"
    secrets:
      repo_token: ${{ secrets.DOCUMENTATION_TOKEN }}

  environment:
    name: Environment
    if: ${{ needs.release.outputs.environment != '' }}
    needs:
    - release
    runs-on: ubuntu-latest
    environment: ${{ needs.release.outputs.environment }}
    steps:
    - run: |
        echo "Environment: ${{ needs.release.outputs.environment }}"
